<?php
require_once __DIR__ . '/includes/functions.php';

// Simple report logic: Current Month
$month = date('Y-m');
$income = get_monthly_income(); // This function uses current month hardcoded inside
$expense = get_monthly_expenses(); // Same
$savings = get_total_savings(); // Same

// Top categories
$stmt = $pdo->prepare("SELECT category, SUM(amount) as total FROM transactions WHERE type = 'expense' AND status = 'completed' AND strftime('%Y-%m', transaction_date) = ? GROUP BY category ORDER BY total DESC LIMIT 5");
$stmt->execute([$month]);
$top_expenses = $stmt->fetchAll();

require_once __DIR__ . '/includes/header.php';
require_once __DIR__ . '/includes/nav.php';
?>

<div class="space-y-6">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
            <h1 class="text-2xl font-bold text-jm-primary dark:text-white">Reports</h1>
            <p class="text-gray-500 dark:text-gray-400">Monthly financial summary.</p>
        </div>
        <button onclick="window.print()" class="btn-secondary flex items-center gap-2">
            <i data-lucide="printer" class="w-4 h-4"></i> Print Report
        </button>
    </div>

    <div class="card p-8 print:shadow-none print:border-none">
        <div class="text-center mb-8">
            <h2 class="text-2xl font-bold text-jm-primary dark:text-white">Monthly Financial Report</h2>
            <p class="text-gray-500"><?php echo date('F Y'); ?></p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 text-center">
            <div class="p-4 bg-green-50 rounded-lg dark:bg-green-900/20">
                <p class="text-sm text-gray-500 dark:text-gray-400">Total Income</p>
                <p class="text-xl font-bold text-green-600"><?php echo format_currency($income); ?></p>
            </div>
            <div class="p-4 bg-red-50 rounded-lg dark:bg-red-900/20">
                <p class="text-sm text-gray-500 dark:text-gray-400">Total Expenses</p>
                <p class="text-xl font-bold text-red-600"><?php echo format_currency($expense); ?></p>
            </div>
            <div class="p-4 bg-purple-50 rounded-lg dark:bg-purple-900/20">
                <p class="text-sm text-gray-500 dark:text-gray-400">Net Savings</p>
                <p class="text-xl font-bold text-purple-600"><?php echo format_currency($savings); ?></p>
            </div>
        </div>

        <div class="mb-8">
            <h3 class="text-lg font-bold text-jm-primary dark:text-white mb-4 border-b pb-2">Top Spending Categories</h3>
            <table class="w-full text-left">
                <thead>
                    <tr class="text-gray-500 dark:text-gray-400 text-sm">
                        <th class="py-2">Category</th>
                        <th class="py-2 text-right">Amount</th>
                        <th class="py-2 text-right">% of Total</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100 dark:divide-gray-700">
                    <?php
                    $total_expense = $expense > 0 ? $expense : 1;
                    foreach ($top_expenses as $t):
                        $pct = ($t['total'] / $total_expense) * 100;
                    ?>
                    <tr>
                        <td class="py-3 text-sm font-medium"><?php echo htmlspecialchars($t['category']); ?></td>
                        <td class="py-3 text-sm text-right"><?php echo format_currency($t['total']); ?></td>
                        <td class="py-3 text-sm text-right text-gray-500"><?php echo number_format($pct, 1); ?>%</td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="text-center text-xs text-gray-400 mt-12">
            Generated by JM Solutionss Finance Dashboard on <?php echo date('M d, Y'); ?>
        </div>
    </div>
</div>

<style media="print">
    @page { size: auto;  margin: 0mm; }
    body { background-color: white; }
    nav, aside, header { display: none !important; }
    .card { box-shadow: none; border: none; }
    .btn-secondary { display: none; }
</style>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
